CopyFile /etc/firewalld/helpers/Q.931.xml
CopyFile /etc/firewalld/helpers/RAS.xml
CopyFile /etc/firewalld/helpers/amanda.xml
CopyFile /etc/firewalld/helpers/ftp.xml
CopyFile /etc/firewalld/helpers/h323.xml
CopyFile /etc/firewalld/helpers/irc.xml
CopyFile /etc/firewalld/helpers/netbios-ns.xml
CopyFile /etc/firewalld/helpers/pptp.xml
CopyFile /etc/firewalld/helpers/proto-gre.xml
CopyFile /etc/firewalld/helpers/sane.xml
CopyFile /etc/firewalld/helpers/sip.xml
CopyFile /etc/firewalld/helpers/snmp.xml
CopyFile /etc/firewalld/helpers/tftp.xml
CopyFile /etc/firewalld/icmptypes/address-unreachable.xml
CopyFile /etc/firewalld/icmptypes/bad-header.xml
CopyFile /etc/firewalld/icmptypes/beyond-scope.xml
CopyFile /etc/firewalld/icmptypes/communication-prohibited.xml
CopyFile /etc/firewalld/icmptypes/destination-unreachable.xml
CopyFile /etc/firewalld/icmptypes/echo-reply.xml
CopyFile /etc/firewalld/icmptypes/echo-request.xml
CopyFile /etc/firewalld/icmptypes/failed-policy.xml
CopyFile /etc/firewalld/icmptypes/fragmentation-needed.xml
CopyFile /etc/firewalld/icmptypes/host-precedence-violation.xml
CopyFile /etc/firewalld/icmptypes/host-prohibited.xml
CopyFile /etc/firewalld/icmptypes/host-redirect.xml
CopyFile /etc/firewalld/icmptypes/host-unknown.xml
CopyFile /etc/firewalld/icmptypes/host-unreachable.xml
CopyFile /etc/firewalld/icmptypes/ip-header-bad.xml
CopyFile /etc/firewalld/icmptypes/mld-listener-done.xml
CopyFile /etc/firewalld/icmptypes/mld-listener-query.xml
CopyFile /etc/firewalld/icmptypes/mld-listener-report.xml
CopyFile /etc/firewalld/icmptypes/mld2-listener-report.xml
CopyFile /etc/firewalld/icmptypes/neighbour-advertisement.xml
CopyFile /etc/firewalld/icmptypes/neighbour-solicitation.xml
CopyFile /etc/firewalld/icmptypes/network-prohibited.xml
CopyFile /etc/firewalld/icmptypes/network-redirect.xml
CopyFile /etc/firewalld/icmptypes/network-unknown.xml
CopyFile /etc/firewalld/icmptypes/network-unreachable.xml
CopyFile /etc/firewalld/icmptypes/no-route.xml
CopyFile /etc/firewalld/icmptypes/packet-too-big.xml
CopyFile /etc/firewalld/icmptypes/parameter-problem.xml
CopyFile /etc/firewalld/icmptypes/port-unreachable.xml
CopyFile /etc/firewalld/icmptypes/precedence-cutoff.xml
CopyFile /etc/firewalld/icmptypes/protocol-unreachable.xml
CopyFile /etc/firewalld/icmptypes/redirect.xml
CopyFile /etc/firewalld/icmptypes/reject-route.xml
CopyFile /etc/firewalld/icmptypes/required-option-missing.xml
CopyFile /etc/firewalld/icmptypes/router-advertisement.xml
CopyFile /etc/firewalld/icmptypes/router-solicitation.xml
CopyFile /etc/firewalld/icmptypes/source-quench.xml
CopyFile /etc/firewalld/icmptypes/source-route-failed.xml
CopyFile /etc/firewalld/icmptypes/time-exceeded.xml
CopyFile /etc/firewalld/icmptypes/timestamp-reply.xml
CopyFile /etc/firewalld/icmptypes/timestamp-request.xml
CopyFile /etc/firewalld/icmptypes/tos-host-redirect.xml
CopyFile /etc/firewalld/icmptypes/tos-host-unreachable.xml
CopyFile /etc/firewalld/icmptypes/tos-network-redirect.xml
CopyFile /etc/firewalld/icmptypes/tos-network-unreachable.xml
CopyFile /etc/firewalld/icmptypes/ttl-zero-during-reassembly.xml
CopyFile /etc/firewalld/icmptypes/ttl-zero-during-transit.xml
CopyFile /etc/firewalld/icmptypes/unknown-header-type.xml
CopyFile /etc/firewalld/icmptypes/unknown-option.xml
CopyFile /etc/firewalld/policies/allow-host-ipv6.xml
CopyFile /etc/firewalld/policies/allow-host-ipv6.xml.old
CopyFile /etc/firewalld/services/0-AD.xml
CopyFile /etc/firewalld/services/RH-Satellite-6-capsule.xml
CopyFile /etc/firewalld/services/RH-Satellite-6.xml
CopyFile /etc/firewalld/services/afp.xml
CopyFile /etc/firewalld/services/alvr.xml
CopyFile /etc/firewalld/services/amanda-client.xml
CopyFile /etc/firewalld/services/amanda-k5-client.xml
CopyFile /etc/firewalld/services/amqp.xml
CopyFile /etc/firewalld/services/amqps.xml
CopyFile /etc/firewalld/services/anno-1602.xml
CopyFile /etc/firewalld/services/anno-1800.xml
CopyFile /etc/firewalld/services/apcupsd.xml
CopyFile /etc/firewalld/services/audit.xml
CopyFile /etc/firewalld/services/ausweisapp2.xml
CopyFile /etc/firewalld/services/bacula-client.xml
CopyFile /etc/firewalld/services/bacula.xml
CopyFile /etc/firewalld/services/bareos-director.xml
CopyFile /etc/firewalld/services/bareos-filedaemon.xml
CopyFile /etc/firewalld/services/bareos-storage.xml
CopyFile /etc/firewalld/services/bb.xml
CopyFile /etc/firewalld/services/bgp.xml
CopyFile /etc/firewalld/services/bitcoin-rpc.xml
CopyFile /etc/firewalld/services/bitcoin-testnet-rpc.xml
CopyFile /etc/firewalld/services/bitcoin-testnet.xml
CopyFile /etc/firewalld/services/bitcoin.xml
CopyFile /etc/firewalld/services/bittorrent-lsd.xml
CopyFile /etc/firewalld/services/ceph-exporter.xml
CopyFile /etc/firewalld/services/ceph-mon.xml
CopyFile /etc/firewalld/services/ceph.xml
CopyFile /etc/firewalld/services/cfengine.xml
CopyFile /etc/firewalld/services/checkmk-agent.xml
CopyFile /etc/firewalld/services/civilization-iv.xml
CopyFile /etc/firewalld/services/civilization-v.xml
CopyFile /etc/firewalld/services/cockpit.xml
CopyFile /etc/firewalld/services/collectd.xml
CopyFile /etc/firewalld/services/condor-collector.xml
CopyFile /etc/firewalld/services/cratedb.xml
CopyFile /etc/firewalld/services/ctdb.xml
CopyFile /etc/firewalld/services/dds-multicast.xml
CopyFile /etc/firewalld/services/dds-unicast.xml
CopyFile /etc/firewalld/services/dds.xml
CopyFile /etc/firewalld/services/dhcp.xml
CopyFile /etc/firewalld/services/dhcpv6-client.xml
CopyFile /etc/firewalld/services/dhcpv6.xml
CopyFile /etc/firewalld/services/distcc.xml
CopyFile /etc/firewalld/services/dns-over-quic.xml
CopyFile /etc/firewalld/services/dns-over-tls.xml
CopyFile /etc/firewalld/services/dns.xml
CopyFile /etc/firewalld/services/docker-registry.xml
CopyFile /etc/firewalld/services/docker-swarm.xml
CopyFile /etc/firewalld/services/dropbox-lansync.xml
CopyFile /etc/firewalld/services/elasticsearch.xml
CopyFile /etc/firewalld/services/etcd-client.xml
CopyFile /etc/firewalld/services/etcd-server.xml
CopyFile /etc/firewalld/services/factorio.xml
CopyFile /etc/firewalld/services/finger.xml
CopyFile /etc/firewalld/services/foreman-proxy.xml
CopyFile /etc/firewalld/services/foreman.xml
CopyFile /etc/firewalld/services/freeipa-4.xml
CopyFile /etc/firewalld/services/freeipa-ldap.xml
CopyFile /etc/firewalld/services/freeipa-ldaps.xml
CopyFile /etc/firewalld/services/freeipa-replication.xml
CopyFile /etc/firewalld/services/freeipa-trust.xml
CopyFile /etc/firewalld/services/ftp.xml
CopyFile /etc/firewalld/services/galera.xml
CopyFile /etc/firewalld/services/ganglia-client.xml
CopyFile /etc/firewalld/services/ganglia-master.xml
CopyFile /etc/firewalld/services/git.xml
CopyFile /etc/firewalld/services/gpsd.xml
CopyFile /etc/firewalld/services/grafana.xml
CopyFile /etc/firewalld/services/gre.xml
CopyFile /etc/firewalld/services/high-availability.xml
CopyFile /etc/firewalld/services/http.xml
CopyFile /etc/firewalld/services/http3.xml
CopyFile /etc/firewalld/services/https.xml
CopyFile /etc/firewalld/services/ident.xml
CopyFile /etc/firewalld/services/imap.xml
CopyFile /etc/firewalld/services/imaps.xml
CopyFile /etc/firewalld/services/ipfs.xml
CopyFile /etc/firewalld/services/ipp-client.xml
CopyFile /etc/firewalld/services/ipp.xml
CopyFile /etc/firewalld/services/ipsec.xml
CopyFile /etc/firewalld/services/irc.xml
CopyFile /etc/firewalld/services/ircs.xml
CopyFile /etc/firewalld/services/iscsi-target.xml
CopyFile /etc/firewalld/services/isns.xml
CopyFile /etc/firewalld/services/jenkins.xml
CopyFile /etc/firewalld/services/kadmin.xml
CopyFile /etc/firewalld/services/kdeconnect.xml
CopyFile /etc/firewalld/services/kerberos.xml
CopyFile /etc/firewalld/services/kibana.xml
CopyFile /etc/firewalld/services/klogin.xml
CopyFile /etc/firewalld/services/kpasswd.xml
CopyFile /etc/firewalld/services/kprop.xml
CopyFile /etc/firewalld/services/kshell.xml
CopyFile /etc/firewalld/services/kube-api.xml
CopyFile /etc/firewalld/services/kube-apiserver.xml
CopyFile /etc/firewalld/services/kube-control-plane-secure.xml
CopyFile /etc/firewalld/services/kube-control-plane.xml
CopyFile /etc/firewalld/services/kube-controller-manager-secure.xml
CopyFile /etc/firewalld/services/kube-controller-manager.xml
CopyFile /etc/firewalld/services/kube-nodeport-services.xml
CopyFile /etc/firewalld/services/kube-scheduler-secure.xml
CopyFile /etc/firewalld/services/kube-scheduler.xml
CopyFile /etc/firewalld/services/kube-worker.xml
CopyFile /etc/firewalld/services/kubelet-readonly.xml
CopyFile /etc/firewalld/services/kubelet-worker.xml
CopyFile /etc/firewalld/services/kubelet.xml
CopyFile /etc/firewalld/services/ldap.xml
CopyFile /etc/firewalld/services/ldaps.xml
CopyFile /etc/firewalld/services/libvirt-tls.xml
CopyFile /etc/firewalld/services/libvirt.xml
CopyFile /etc/firewalld/services/lightning-network.xml
CopyFile /etc/firewalld/services/llmnr-client.xml
CopyFile /etc/firewalld/services/llmnr-tcp.xml
CopyFile /etc/firewalld/services/llmnr-udp.xml
CopyFile /etc/firewalld/services/llmnr.xml
CopyFile /etc/firewalld/services/managesieve.xml
CopyFile /etc/firewalld/services/matrix.xml
CopyFile /etc/firewalld/services/mdns.xml
CopyFile /etc/firewalld/services/memcache.xml
CopyFile /etc/firewalld/services/minecraft.xml
CopyFile /etc/firewalld/services/minidlna.xml
CopyFile /etc/firewalld/services/mongodb.xml
CopyFile /etc/firewalld/services/mosh.xml
CopyFile /etc/firewalld/services/mountd.xml
CopyFile /etc/firewalld/services/mqtt-tls.xml
CopyFile /etc/firewalld/services/mqtt.xml
CopyFile /etc/firewalld/services/ms-wbt.xml
CopyFile /etc/firewalld/services/mssql.xml
CopyFile /etc/firewalld/services/murmur.xml
CopyFile /etc/firewalld/services/mysql.xml
CopyFile /etc/firewalld/services/nbd.xml
CopyFile /etc/firewalld/services/nebula.xml
CopyFile /etc/firewalld/services/need-for-speed-most-wanted.xml
CopyFile /etc/firewalld/services/netbios-ns.xml
CopyFile /etc/firewalld/services/netdata-dashboard.xml
CopyFile /etc/firewalld/services/nfs.xml
CopyFile /etc/firewalld/services/nfs3.xml
CopyFile /etc/firewalld/services/nmea-0183.xml
CopyFile /etc/firewalld/services/nrpe.xml
CopyFile /etc/firewalld/services/ntp.xml
CopyFile /etc/firewalld/services/nut.xml
CopyFile /etc/firewalld/services/opentelemetry.xml
CopyFile /etc/firewalld/services/openvpn.xml
CopyFile /etc/firewalld/services/ovirt-imageio.xml
CopyFile /etc/firewalld/services/ovirt-storageconsole.xml
CopyFile /etc/firewalld/services/ovirt-vmconsole.xml
CopyFile /etc/firewalld/services/plex.xml
CopyFile /etc/firewalld/services/pmcd.xml
CopyFile /etc/firewalld/services/pmproxy.xml
CopyFile /etc/firewalld/services/pmwebapi.xml
CopyFile /etc/firewalld/services/pmwebapis.xml
CopyFile /etc/firewalld/services/pop3.xml
CopyFile /etc/firewalld/services/pop3s.xml
CopyFile /etc/firewalld/services/postgresql.xml
CopyFile /etc/firewalld/services/privoxy.xml
CopyFile /etc/firewalld/services/prometheus-node-exporter.xml
CopyFile /etc/firewalld/services/prometheus.xml
CopyFile /etc/firewalld/services/proxy-dhcp.xml
CopyFile /etc/firewalld/services/ps2link.xml
CopyFile /etc/firewalld/services/ps3netsrv.xml
CopyFile /etc/firewalld/services/ptp.xml
CopyFile /etc/firewalld/services/pulseaudio.xml
CopyFile /etc/firewalld/services/puppetmaster.xml
CopyFile /etc/firewalld/services/quassel.xml
CopyFile /etc/firewalld/services/radius.xml
CopyFile /etc/firewalld/services/rdp.xml
CopyFile /etc/firewalld/services/redis-sentinel.xml
CopyFile /etc/firewalld/services/redis.xml
CopyFile /etc/firewalld/services/rpc-bind.xml
CopyFile /etc/firewalld/services/rquotad.xml
CopyFile /etc/firewalld/services/rsh.xml
CopyFile /etc/firewalld/services/rsyncd.xml
CopyFile /etc/firewalld/services/rtsp.xml
CopyFile /etc/firewalld/services/salt-master.xml
CopyFile /etc/firewalld/services/samba-client.xml
CopyFile /etc/firewalld/services/samba-dc.xml
CopyFile /etc/firewalld/services/samba.xml
CopyFile /etc/firewalld/services/sane.xml
CopyFile /etc/firewalld/services/settlers-history-collection.xml
CopyFile /etc/firewalld/services/sip.xml
CopyFile /etc/firewalld/services/sips.xml
CopyFile /etc/firewalld/services/slp.xml
CopyFile /etc/firewalld/services/smtp-submission.xml
CopyFile /etc/firewalld/services/smtp.xml
CopyFile /etc/firewalld/services/smtps.xml
CopyFile /etc/firewalld/services/snmp.xml
CopyFile /etc/firewalld/services/snmptls-trap.xml
CopyFile /etc/firewalld/services/snmptls.xml
CopyFile /etc/firewalld/services/snmptrap.xml
CopyFile /etc/firewalld/services/spideroak-lansync.xml
CopyFile /etc/firewalld/services/spotify-sync.xml
CopyFile /etc/firewalld/services/squid.xml
CopyFile /etc/firewalld/services/ssdp.xml
CopyFile /etc/firewalld/services/ssh.xml
CopyFile /etc/firewalld/services/statsrv.xml
CopyFile /etc/firewalld/services/steam-streaming.xml
CopyFile /etc/firewalld/services/stellaris.xml
CopyFile /etc/firewalld/services/stronghold-crusader.xml
CopyFile /etc/firewalld/services/submission.xml
CopyFile /etc/firewalld/services/supertuxkart.xml
CopyFile /etc/firewalld/services/svdrp.xml
CopyFile /etc/firewalld/services/svn.xml
CopyFile /etc/firewalld/services/syncthing-gui.xml
CopyFile /etc/firewalld/services/syncthing-relay.xml
CopyFile /etc/firewalld/services/syncthing.xml
CopyFile /etc/firewalld/services/synergy.xml
CopyFile /etc/firewalld/services/syscomlan.xml
CopyFile /etc/firewalld/services/syslog-tls.xml
CopyFile /etc/firewalld/services/syslog.xml
CopyFile /etc/firewalld/services/telnet.xml
CopyFile /etc/firewalld/services/tentacle.xml
CopyFile /etc/firewalld/services/terraria.xml
CopyFile /etc/firewalld/services/tftp.xml
CopyFile /etc/firewalld/services/tile38.xml
CopyFile /etc/firewalld/services/tinc.xml
CopyFile /etc/firewalld/services/tor-socks.xml
CopyFile /etc/firewalld/services/transmission-client.xml
CopyFile /etc/firewalld/services/upnp-client.xml
CopyFile /etc/firewalld/services/vdsm.xml
CopyFile /etc/firewalld/services/vnc-server.xml
CopyFile /etc/firewalld/services/vrrp.xml
CopyFile /etc/firewalld/services/warpinator.xml
CopyFile /etc/firewalld/services/wbem-http.xml
CopyFile /etc/firewalld/services/wbem-https.xml
CopyFile /etc/firewalld/services/wireguard.xml
CopyFile /etc/firewalld/services/ws-discovery-client.xml
CopyFile /etc/firewalld/services/ws-discovery-tcp.xml
CopyFile /etc/firewalld/services/ws-discovery-udp.xml
CopyFile /etc/firewalld/services/ws-discovery.xml
CopyFile /etc/firewalld/services/wsman.xml
CopyFile /etc/firewalld/services/wsmans.xml
CopyFile /etc/firewalld/services/xdmcp.xml
CopyFile /etc/firewalld/services/xmpp-bosh.xml
CopyFile /etc/firewalld/services/xmpp-client.xml
CopyFile /etc/firewalld/services/xmpp-local.xml
CopyFile /etc/firewalld/services/xmpp-server.xml
CopyFile /etc/firewalld/services/zabbix-agent.xml
CopyFile /etc/firewalld/services/zabbix-java-gateway.xml
CopyFile /etc/firewalld/services/zabbix-server.xml
CopyFile /etc/firewalld/services/zabbix-trapper.xml
CopyFile /etc/firewalld/services/zabbix-web-service.xml
CopyFile /etc/firewalld/services/zero-k.xml
CopyFile /etc/firewalld/services/zerotier.xml
CopyFile /etc/firewalld/zones/block.xml
CopyFile /etc/firewalld/zones/block.xml.old
CopyFile /etc/firewalld/zones/dmz.xml
CopyFile /etc/firewalld/zones/dmz.xml.old
CopyFile /etc/firewalld/zones/docker.xml
CopyFile /etc/firewalld/zones/docker.xml.old
CopyFile /etc/firewalld/zones/drop.xml
CopyFile /etc/firewalld/zones/drop.xml.old
CopyFile /etc/firewalld/zones/external.xml
CopyFile /etc/firewalld/zones/external.xml.old
CopyFile /etc/firewalld/zones/home.xml
CopyFile /etc/firewalld/zones/home.xml.old
CopyFile /etc/firewalld/zones/internal.xml
CopyFile /etc/firewalld/zones/internal.xml.old
CopyFile /etc/firewalld/zones/nm-shared.xml
CopyFile /etc/firewalld/zones/nm-shared.xml.old
CopyFile /etc/firewalld/zones/public.xml
CopyFile /etc/firewalld/zones/public.xml.old
CopyFile /etc/firewalld/zones/trusted.xml
CopyFile /etc/firewalld/zones/trusted.xml.old
CopyFile /etc/firewalld/zones/work.xml
CopyFile /etc/firewalld/zones/work.xml.old
CopyFile /etc/firewalld/lockdown-whitelist.xml.old
